services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    depends_on:
      - redis
      - postgres
    restart: always
    ports:
      - "8080:8080"
    environment:
      - AUTHENTICATION_API_KEY=apikey321
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://postgres:postgres@postgres:5432/postgres
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://redis:6379/6
      - CACHE_REDIS_PREFIX_KEY=evolution
      - CACHE_REDIS_SAVE_INSTANCES=true
      - CACHE_LOCAL_ENABLED=false
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net

  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5441:5432"
    networks:
      - evolution-net
    command: >
      -c 'listen_addresses=*'
      -c 'max_connections=200'
      -c 'shared_buffers=256MB'
      -c 'work_mem=8MB'
      -c 'log_min_messages=WARNING'

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - evolution-net

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    depends_on:
      - postgres
      - redis
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/barbershop_db
      - REDIS_URL=redis://redis:6379/0
      - DJANGO_SETTINGS_MODULE=core.settings
    volumes:
      - ./src:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - evolution-net

volumes:
  evolution_instances:
  postgres_data:

networks:
  evolution-net:
    driver: bridge