"""add foreignkey entry products and employee

Revision ID: 1a84bda4f0d2
Revises: 905555cffb5f
Create Date: 2025-11-14 12:27:07.172248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a84bda4f0d2'
down_revision: Union[str, Sequence[str], None] = '905555cffb5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'product', 'companies', ['company_id'], ['id'])
    op.add_column('products_employees', sa.Column('company_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products_employees', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products_employees', type_='foreignkey')
    op.drop_column('products_employees', 'company_id')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'company_id')
    # ### end Alembic commands ###
