"""add branch company

Revision ID: 20e8d6586667
Revises: 443222914b9e
Create Date: 2026-02-09 12:11:59.898668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e8d6586667'
down_revision: Union[str, Sequence[str], None] = '443222914b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_company',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_company_name'), 'branch_company', ['name'], unique=False)
    op.add_column('employee_companies', sa.Column('branch_company_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'employee_companies', 'branch_company', ['branch_company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee_companies', type_='foreignkey')
    op.drop_column('employee_companies', 'branch_company_id')
    op.drop_index(op.f('ix_branch_company_name'), table_name='branch_company')
    op.drop_table('branch_company')
    # ### end Alembic commands ###