"""remove not null

Revision ID: 29b014333201
Revises: f7152d4a5ad4
Create Date: 2026-02-14 17:55:21.366568

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29b014333201'
down_revision: Union[str, Sequence[str], None] = 'f7152d4a5ad4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'schedule', 'time_start', existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        'schedule', 'time_end', existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'schedule', 'time_end', existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        'schedule', 'time_start', existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###
