"""alter table in schedule

Revision ID: 30028aedb311
Revises: 29b014333201
Create Date: 2026-03-09 10:15:45.125536

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '30028aedb311'
down_revision: Union[str, Sequence[str], None] = '29b014333201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'product_id', existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedule', 'product_id', existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
