"""Add columns passoword, users, owners and employees

Revision ID: 7c82fabbe69c
Revises: 7fe50eda1dd4
Create Date: 2025-11-17 10:51:10.812674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c82fabbe69c'
down_revision: Union[str, Sequence[str], None] = '7fe50eda1dd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column('employees', sa.Column('hashed_password', sa.String(), nullable=True))

    # Preencher com um valor temporário (por exemplo, uma string aleatória)
    op.execute("UPDATE employees SET hashed_password = 'TEMPORARY_PASSWORD' WHERE hashed_password IS NULL")

    # Agora sim, adicionar NOT NULL
    op.alter_column('employees', 'hashed_password', nullable=False)

    op.drop_column('employees', 'session_token')

    op.add_column('owners', sa.Column('hashed_password', sa.String(), nullable=True))
    op.execute("UPDATE owners SET hashed_password = 'TEMP' WHERE hashed_password IS NULL")
    op.alter_column('owners', 'hashed_password', nullable=False)

    op.drop_column('users', 'session_token')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('owners', 'hashed_password')
    op.add_column('employees', sa.Column('session_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('employees', 'hashed_password')
    # ### end Alembic commands ###
