"""Adjust tables

Revision ID: cdd3802fe8df
Revises: 4baea7fa8489
Create Date: 2026-02-10 19:43:11.286180

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdd3802fe8df'
down_revision: Union[str, Sequence[str], None] = '4baea7fa8489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_companies')
    op.create_unique_constraint(None, 'company', ['slug'])
    op.drop_constraint(
        op.f('employee_branch_company_id_fkey'), 'employee', type_='foreignkey'
    )
    op.drop_column('employee', 'branch_company_id')
    op.drop_constraint(
        op.f('schedule_branch_company_id_fkey'), 'schedule', type_='foreignkey'
    )
    op.drop_column('schedule', 'branch_company_id')
    op.drop_constraint(
        op.f('schedule_block_branch_company_id_fkey'),
        'schedule_block',
        type_='foreignkey',
    )
    op.drop_column('schedule_block', 'branch_company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'schedule_block',
        sa.Column('branch_company_id', sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f('schedule_block_branch_company_id_fkey'),
        'schedule_block',
        'branch_company',
        ['branch_company_id'],
        ['id'],
    )
    op.add_column(
        'schedule',
        sa.Column('branch_company_id', sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f('schedule_branch_company_id_fkey'),
        'schedule',
        'branch_company',
        ['branch_company_id'],
        ['id'],
    )
    op.add_column(
        'employee',
        sa.Column('branch_company_id', sa.UUID(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f('employee_branch_company_id_fkey'),
        'employee',
        'branch_company',
        ['branch_company_id'],
        ['id'],
    )
    op.drop_constraint(None, 'company', type_='unique')
    op.create_table(
        'employee_companies',
        sa.Column('employee_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('company_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('branch_company_id', sa.UUID(), autoincrement=False, nullable=True),
        sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            'id',
            sa.UUID(),
            server_default=sa.text('gen_random_uuid()'),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("timezone('utc'::text, now())"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ['branch_company_id'],
            ['branch_company.id'],
            name=op.f('employee_companies_branch_company_id_fkey'),
        ),
        sa.ForeignKeyConstraint(
            ['company_id'],
            ['company.id'],
            name=op.f('employee_companies_company_id_fkey'),
        ),
        sa.ForeignKeyConstraint(
            ['employee_id'],
            ['employee.id'],
            name=op.f('employee_companies_employee_id_fkey'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('employee_companies_pkey')),
    )
    # ### end Alembic commands ###
