"""Add url in service

Revision ID: f7152d4a5ad4
Revises: cdd3802fe8df
Create Date: 2026-02-12 12:23:43.303950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7152d4a5ad4'
down_revision: Union[str, Sequence[str], None] = 'cdd3802fe8df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('url_image', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'url_image')
    # ### end Alembic commands ###